fix: give default throughput value 125 for any type of ebs
Since aws_ebs_volume always checks the range of throughput.
```
Error: expected throughput to be in the range (125 - 1000), got 0
```